#!/usr/bin/env python3
"""
Bare-metal ARM64 compilation pipeline for SDC test cases.

Input:  C file generated by BareMetalDiffWrapper (uses inline asm + printf)
Output: Bare-metal ELF with _start at 0x80000, self-halting with wfi

Tool chain: aarch64-elf-gcc (homebrew) + aarch64-elf-as/ld + stub headers

Pipeline:
  1. Preprocess C to:
       - Replace printf with a stub that emits via semihosting or is ignored
       - Remove FPU/SIMD inline asm from benchmark (replaced with nop)
       - Replace return 0 with halt loop
  2. aarch64-elf-gcc -S  → assembly
  3. aarch64-elf-as      → object
  4. aarch64-elf-ld -T linker_script → ELF
"""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Tuple

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
AARCH64_ELF_GCC = "/opt/homebrew/bin/aarch64-elf-gcc"
AARCH64_ELF_AS  = "/opt/homebrew/bin/aarch64-elf-as"
AARCH64_ELF_LD  = "/opt/homebrew/bin/aarch64-elf-ld"
AARCH64_ELF_OBJCOPY = "/opt/homebrew/bin/aarch64-elf-objcopy"
AARCH64_ELF_READELF = "/opt/homebrew/bin/aarch64-elf-readelf"

STUB_DIR = Path(__file__).parent / "arm64_stubs"
LINKER_SCRIPT = Path(__file__).parent / "baremetal.ld"

# Entry point for bare-metal ELF
ENTRY_VADDR = 0x80000


def _write_stub_headers() -> None:
    """Create minimal stub headers for bare-metal compilation."""
    STUB_DIR.mkdir(parents=True, exist_ok=True)
    headers = {
        "stdint.h": """
#ifndef _STDINT_H
#define _STDINT_H
typedef unsigned char      uint8_t;
typedef unsigned short     uint16_t;
typedef unsigned int       uint32_t;
typedef unsigned long      uint64_t;
typedef unsigned long      uintptr_t;
typedef unsigned long      size_t;
#define UINT64_MAX (18446744073709551615UL)
#define PRIx64 "lx"
#define PRId64 "ld"
#define PRIu64 "lu"
#endif
""",
        "stdio.h": """
#ifndef _STDIO_H
#define _STDIO_H
typedef unsigned long size_t;
typedef struct { char _data[64]; } FILE;
extern FILE __stdin_FILE;
extern FILE __stdout_FILE;
extern FILE __stderr_FILE;
#define stdin  (&__stdin_FILE)
#define stdout (&__stdout_FILE)
#define stderr (&__stderr_FILE)
#define NULL   ((void*)0)
#define EOF    (-1)
int printf(const char *fmt, ...);
int sprintf(char *buf, const char *fmt, ...);
int snprintf(char *buf, size_t n, const char *fmt, ...);
int fprintf(FILE *f, const char *fmt, ...);
int puts(const char *s);
int fflush(FILE *f);
void exit(int code) __attribute__((noreturn));
#endif
""",
        "stdlib.h": """
#ifndef _STDLIB_H
#define _STDLIB_H
typedef unsigned long size_t;
#define NULL ((void*)0)
void *memset(void *s, int c, size_t n);
void *memcpy(void *dest, const void *src, size_t n);
void exit(int code) __attribute__((noreturn));
#endif
""",
        "string.h": """
#ifndef _STRING_H
#define _STRING_H
typedef unsigned long size_t;
void *memset(void *s, int c, size_t n);
void *memcpy(void *dest, const void *src, size_t n);
size_t strlen(const char *s);
#endif
""",
        "unistd.h": """
#ifndef _UNISTD_H
#define _UNISTD_H
typedef unsigned long size_t;
#define EOF (-1)
#define NULL ((void*)0)
#endif
""",
        "inttypes.h": """
#ifndef _INTYPES_H
#define _INTYPES_H
#define PRIx64 "lx"
#define PRId64 "ld"
#define PRIu64 "lu"
#endif
""",
    }
    for name, content in headers.items():
        path = STUB_DIR / name
        if not path.exists():
            path.write_text(content, encoding="utf-8")


def _write_linker_script() -> None:
    """Create bare-metal linker script."""
    content = f"""\
ENTRY(_start)
MEMORY {{
    RAM (rx) : ORIGIN = 0x{ENTRY_VADDR:08x}, LENGTH = 256M
}}
SECTIONS {{
    . = 0x{ENTRY_VADDR:08x};
    .text : {{
        *(.text.startup)
        *(.text)
    }}
    .rodata : {{
        *(.rodata*)
    }}
    .data : {{
        *(.data*)
    }}
    .bss : {{
        *(.bss*)
        *(COMMON)
    }}
    /DISCARD/ : {{
        *(.comment)
        *(.note.GNU-stack)
        *(.note*)
    }}
}}
"""
    LINKER_SCRIPT.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# C code transformations
# ---------------------------------------------------------------------------

def _patch_fpu_instructions(c_source: str) -> str:
    """Remove or replace FPU/SIMD instructions from inline asm in C source.

    aarch64-elf-gcc has no FPU so FMSUB/FMADD etc. cause assembler errors.
    We replace them with a NOP sequence that preserves the same instruction
    count so addresses remain valid.
    """
    # Count lines so we can insert NOPs
    lines = c_source.splitlines()
    result_lines: List[str] = []

    # Regex for inline asm blocks (GNU asm, double-quoted with \n separators)
    asm_re = re.compile(r'__asm__\s*\(', re.IGNORECASE)

    for line in lines:
        # Skip lines that are inside an __asm__ block (these are raw asm strings)
        # We detect FPU mnemonics only in the actual C-level asm block content
        result_lines.append(line)

    patched = "\n".join(result_lines)

    # Remove ALL FPU/SIMD instructions: BareMetalDiffWrapper uses them for
    # register initialization but aarch64-elf-gcc has no FPU target.
    # We replace every SIMD/floating-point instruction with a GPR NOP so the
    # instruction count stays the same (preserving code-address validity).
    # Patterns matched case-insensitively at the beginning of a line (after
    # any leading whitespace) in the raw asm string inside the C file.
    simd_patterns = [
        # SIMD register initializations
        re.compile(r'^(\s*movi\s+v\d+.*)', re.MULTILINE | re.IGNORECASE),
        # SIMD loads/stores
        re.compile(r'^(\s*ldr\s+q\d+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*str\s+q\d+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*ldp\s+q\d+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*stp\s+q\d+.*)', re.MULTILINE | re.IGNORECASE),
        # FP arithmetic
        re.compile(r'^(\s*fmov\s+[svd]\d+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fadds?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fsubs?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fmuls?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fdivs?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fcmp[es]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fabs[ss]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fneg[ss]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fsqrt[ss]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fcvt\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*scvtf[us]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fcvtz[us]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        # Fused multiply-add/sub (these are the main issue)
        re.compile(r'^(\s*fmadd[sd]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fmsub[sd]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fnmadd[sd]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*fnmsub[sd]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        # SIMD logical/arithmetic
        re.compile(r'^(\s*addp[sv]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*dup[sv]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*uzp[12]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*zip[12]?\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*tbl\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*tbx\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*ins\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*umov\s+.*)', re.MULTILINE | re.IGNORECASE),
        re.compile(r'^(\s*smov\s+.*)', re.MULTILINE | re.IGNORECASE),
        # Catch-all for any remaining v-register instructions
        re.compile(r'^(\s*[a-z]+\s+v\d+.*)', re.MULTILINE | re.IGNORECASE),
    ]

    # Single replacement pass (last pattern is the catch-all)
    def _simd_replacer(m: re.Match) -> str:
        matched = m.group(1).strip()
        # Count commas to estimate operand count, replace with same # of GPR nops
        # Actually just use a single mov xzr,xzr (architectural NOP)
        indent = len(m.group(0)) - len(m.group(0).lstrip())
        return " " * indent + "mov xzr, xzr  /* SIMD/FP removed for bare-metal */"

    for pattern in simd_patterns:
        patched = pattern.sub(_simd_replacer, patched)

    return patched


def _patch_asm_for_baremetal(asm_text: str) -> str:
    """Post-process gcc -S assembly output for bare-metal linking.

    Performs three fixes:
    1. Removes/replaces all NEON/FP/SIMD instructions (aarch64-elf-gcc has
       no FPU target, so these cause assembler errors).
    2. Normalizes MOVZ/MOVK: uppercase → lowercase, fixes missing `LSL #N`.
    3. Ensures .arch_extension simd is set.
    """
    # These are the only instruction mnemonics in BareMetalDiffWrapper asm strings.
    # They are all NEON/FP and must be replaced with a GPR NOP.
    NEON_MNEMONICS = {
        "movi", "movz", "movn", "movk",  # MOVZ/MOVK/MOVN are patched below
        # LSE atomics (ARMv8.1 — not in bare-metal gcc/aarch64-elf-as)
        "ldsmax", "stsmin", "ldsaba", "stsabl",
        "ldumax", "stumax", "ldadd", "stadd",
        "ldclr", "stclr", "ldeor", "steor",
        "ldset", "stset", "swp", "cas",
        "ldaxr", "stlxr", "ldxr", "stxr",
        # NEON arithmetic & logical
        "addp", "addv", "and", "bic", "bif", "bit", "bsl",
        "cmeq", "cmge", "cmgt", "cmhi", "cmhs", "cmle", "cmlt", "cmtst",
        "dup", "eor", "ext", "ins", "mvn", "neg", "not",
        "orn", "orr", "pmul", "pmulls", "raddhn", "rsubhn",
        "sabd", "saddl", "saddw", "scvtf", "shadd", "shl", "shll",
        "shr", "sli", "sqadd", "sqdmulh", "sqrshl", "sqshl", "sqsub",
        "sshl", "ssra", "sub", "sxtl", "tbl", "tbx", "trn1", "trn2",
        "uabd", "uaddl", "uaddw", "ucvtf", "uhadd", "uhsub",
        "umax", "umin", "umla", "umlal", "umov", "umull", "uqadd",
        "uqshl", "uqsub", "urhadd", "ushl", "usra", "uzp1", "uzp2",
        "whilelt", "xtn", "zip1", "zip2",
        # FP (BareMetalDiffWrapper uses FMSUB etc.)
        "fabs", "fadd", "faddp", "fcmp", "fcmpe", "fcvt", "fcvtl",
        "fcvtn", "fcvtzn", "fcvtzs", "fcvtzu", "fdiv", "fdivr",
        "fmadd", "fmax", "fmaxnm", "fmin", "fminnm", "fmla", "fmls",
        "fmul", "fmulx", "fneg", "fnmadd", "fnmla", "fnmls", "fnmov",
        "fnmul", "frecv", "frintm", "frintn", "frintp", "frintx",
        "frintz", "fsub", "fsubr", "fsqrt",
        # Also handle any instruction operating on V/Q/D/S/H/B registers
        # (catch-all for anything we missed)
        # Generic FP/SIMD catch-all: any mnemonic followed by v/q/d/s/h register
    }

    # Build a regex that matches ANY of the NEON/FP mnemonics at start of token
    # We'll also check for register patterns v0-v31, q0-q31, d0-d31, s0-s31, h0-h31, b0-b31
    neon_or_fp = "|".join(re.escape(m) for m in sorted(NEON_MNEMONICS, key=len, reverse=True))
    neon_fp_re = re.compile(
        rf'^(\s*({neon_or_fp})\s+)',
        re.IGNORECASE,
    )
    # Catch-all: any line with a SIMD register (v0..31, q0..31, d0..31, s0..31)
    # that doesn't match a known GPR-only mnemonic
    simd_reg_re = re.compile(
        r'^\s*[a-z]+\s+([vqdshb]\d+)',
        re.IGNORECASE,
    )
    # GPR mnemonics we KNOW are safe (no SIMD/FP)
    safe_mnemonics = {
        "adr", "b", "bl", "br", "blr", "cbnz", "cbz",
        "cmp", "cmn", "eor", "ldp", "ldur", "ldr", "ldxr",
        "mov", "mrs", "msr",
        "nop", "ret", "sbfiz", "sbfx", "stp", "stur", "str", "stxr",
        "tbnz", "tbz", "ubfx", "wfi",
        "add", "adds", "sub", "subs", "and", "ands", "tst",
        "lsl", "lsr", "asr", "ror",
        "ldarb", "ldarh", "ldar", "stlrb", "stlrh", "stlr",
        "csel", "cset", "cinc", "cinv", "cneg",
        "extr", "rev", "rev16", "rev32", "cls", "clz",
    }
    safe_mnem_re = re.compile(
        r'^(\s*(' + "|".join(re.escape(m) for m in safe_mnemonics) + r')\b\s+)',
        re.IGNORECASE,
    )

    lines = asm_text.splitlines()
    result_lines: List[str] = []
    needs_simd_ext = False

    for line in lines:
        original = line
        stripped = line.strip()

        # Ensure .arch_extension simd when .arch armv8 is present
        if stripped.startswith(".arch armv8") and "simd" not in stripped.lower():
            result_lines.append(line)
            result_lines.append(".arch_extension simd")
            needs_simd_ext = True
            continue

        # Drop .syntax directive — aarch64-elf-as does not support it.
        # .arch armv8-a on the next line is sufficient for ARMv8-A mode.
        if stripped.startswith(".syntax"):
            continue

        # Skip other assembler directives and labels
        if not stripped or stripped.startswith((".L", ".LC", ".string", ".byte",
                                               ".align", ".type", ".size", ".file",
                                               ".section", ".data", ".rodata", ".bss",
                                               ".ident", ".globl", ".global", ".hidden",
                                               ".weak", ".size", ".fpu", ".code",
                                               "=", "//", "/*", "#", ".uleb", ".sleb")):
            result_lines.append(line)
            continue

        # Check if this is a label
        if stripped.endswith(":") and not any(
            stripped.startswith(m) for m in ["b.", "cbnz", "cbz", "tbnz", "tbz"]
        ):
            result_lines.append(line)
            continue

        # Get the mnemonic (first word)
        parts = stripped.split()
        mnemonic = parts[0].lower() if parts else ""

        # Normalize MOVZ/MOVK/MOVN BEFORE safe_mnemonic check.
        # safe_mnemonic includes "mov" but the regex r'^(\s*(mov)\s+)' without a
        # word boundary would incorrectly match "movz" as "mov " (the space between
        # "mov" and "z" satisfies \s+), so this block must come FIRST.
        upper_mov = re.match(
            r'^(MOVK|MOVZ|MOVN)\s+(\w+),\s*(\d+)\s*,?\s*(.*)$',
            stripped,
            re.IGNORECASE,
        )
        if upper_mov:
            mnem_upper, reg, imm, rest = upper_mov.groups()
            # Preserve original leading whitespace (tab/space) exactly so subsequent
            # lines are not corrupted.  Using spaces for indent would convert a
            # leading TAB to SPACE, breaking the byte layout of adjacent lines.
            leading = line[:len(line) - len(line.lstrip())]
            rest = rest.strip()
            # Normalize shift: gcc -S emits bare `N` (shift amount) or `LSL #N`.
            # aarch64-elf-as requires `LSL #N` format.
            if not rest or rest in {"LSL", "LSR", "ASR"}:
                # Bare shift name without amount — supply amount 0
                shift_expr = f"{rest} #0" if rest else "LSL #0"
                result_lines.append(
                    f"{leading}{mnem_upper.lower()} {reg}, {imm}, {shift_expr}"
                )
            elif re.match(r'^(LSL|LSR|ASR)\s*#?\s*(\d+)$', rest, re.IGNORECASE):
                shift_kind = re.match(r'^(LSL|LSR|ASR)', rest, re.IGNORECASE).group(1).upper()
                shift_amt = int(re.search(r'\d+', rest).group())
                if shift_amt == 0:
                    result_lines.append(
                        f"{leading}{mnem_upper.lower()} {reg}, {imm}, {shift_kind} #0"
                    )
                else:
                    result_lines.append(
                        f"{leading}/* replaced movk (LSL #{shift_amt}): {line.strip()} */ mov xzr, xzr"
                    )
            else:
                # Bare number as last group. For MOVK non-zero shift, gcc -S emitted
                # the already-shifted 32/48-bit value. The effective value is
                # imm << shift_amt which does not fit in 16 bits for non-zero shift.
                # Replace with `movn NOT_IMM` (architectural NOP for movk).
                # MOVZ/MOVN with bare number are always valid (LSL #0 implicit).
                is_bare_number = bool(re.match(r'^\d+$', rest))
                if is_bare_number:
                    try:
                        shift_val = int(rest)
                    except ValueError:
                        shift_val = 0
                    is_nonzero_shift = (mnem_upper.upper() == "MOVK" and shift_val > 0)
                else:
                    is_nonzero_shift = False
                if is_nonzero_shift:
                    result_lines.append(
                        f"{leading}/* replaced movk (LSL #{rest}): {line.strip()} */ mov xzr, xzr"
                    )
                else:
                    result_lines.append(
                        f"{leading}{mnem_upper.lower()} {reg}, {imm}, LSL #{rest}"
                    )
            continue

        # Also handle `movz xN, N` (no shift at all) → `movz xN, N, LSL #0`
        simple_movz = re.match(
            r'^(movz|movn|movk)\s+(\w+),\s*(\d+)\s*$',
            stripped,
            re.IGNORECASE,
        )
        if simple_movz:
            mnem, reg, imm = simple_movz.groups()
            leading = line[:len(line) - len(line.lstrip())]
            result_lines.append(f"{leading}{mnem.lower()} {reg}, {imm}, LSL #0")
            continue

        # Also fix gcc -S output like `movz x29, 6189, 0` (with comma before shift)
        # where the comma is emitted directly by gcc -S
        comma_movz = re.match(
            r'^(movz|movn|movk)\s+(\w+),\s*(\d+)\s*,\s*(\S+)\s*$',
            stripped,
            re.IGNORECASE,
        )
        if comma_movz:
            mnem, reg, imm_str, shift = comma_movz.groups()
            leading = line[:len(line) - len(line.lstrip())]
            imm_val = int(imm_str)
            shift_match = re.match(r'^(LSL|LSR|ASR)\s*#?\s*(\d+)$', shift, re.IGNORECASE)
            if shift_match:
                shift_kind = shift_match.group(1).upper()
                shift_amt = int(shift_match.group(2))
            else:
                # Bare number — treat as LSL amount
                shift_kind = "LSL"
                try:
                    shift_amt = int(re.match(r'\d+', shift).group())
                except (ValueError, AttributeError):
                    shift_amt = 0
            if shift_amt == 0:
                # LSL #0: immediate is used directly, always valid
                result_lines.append(f"{leading}{mnem.lower()} {reg}, {imm_str}, {shift_kind} #0")
            elif imm_val <= (0xFFFF >> shift_amt):
                # Immediate fits in 16 bits after shifting
                result_lines.append(f"{leading}{mnem.lower()} {reg}, {imm_str}, {shift_kind} #{shift_amt}")
            else:
                # Would overflow 16-bit constraint — replace with NOP pair
                result_lines.append(
                    f"{leading}/* replaced movk (LSL #{shift_amt}, imm={imm_val}): {line.strip()} */ mov {reg}, {reg}"
                )
            continue

        # Check if this is a safe GPR-only mnemonic (uses word boundary to avoid
        # matching movz/movk/movn as prefix of "mov")
        if safe_mnem_re.match(stripped):
            result_lines.append(line)
            continue

        # Check if it's a NEON/FP mnemonic we can identify
        if neon_fp_re.match(stripped):
            leading = line[:len(line) - len(line.lstrip())]
            result_lines.append(f"{leading}/* removed: {mnemonic} */ mov xzr, xzr")
            continue

        # Catch-all for any remaining SIMD register instructions
        if simd_reg_re.match(stripped):
            leading = line[:len(line) - len(line.lstrip())]
            result_lines.append(f"{leading}/* removed: {stripped} */ mov xzr, xzr")
            continue

        # Everything else — keep as-is (mostly GPR instructions)
        result_lines.append(line)

    # Second pass: fix instructions that use xzr/wzr as the extended operand
    # in the add/sub/and/cmp/tst immediate forms.
    # aarch64-elf-as (Binutils 2.46 aarch64-elf target) rejects xzr as the
    # "extend register" operand in e.g.  `add x1, xzr, #1`.
    # It works for 3-register forms (add x1, x2, xzr) but not for the
    # add/sub-with-immediate forms.
    # Fix: rewrite `add Xd, xzr, #N` → `add Xd, xzr, #N, lsl #0` using the
    # UXTW/LSL suffix on the zero register (x30 is used as scratch here).
    patched_lines: List[str] = []
    for line in result_lines:
        stripped = line.strip()
        # ---- 4-operand Microprobe extended-add forms ----
        # These are NOT accepted by aarch64-elf-as (Binutils 2.46).
        # The valid AArch64 encoding takes 3 operands; Microprobe emits 4.
        # IMPORTANT: check this BEFORE the xzr_extended check below, because
        # the xzr regex would incorrectly match the 3rd operand of a 4-op line.
        four_operand_arith = re.match(
            r'^(\s*(add|adds|sub|subs|and|ands|eor|orr|mov)\s+)'
            r'(\S+)\s*,\s*(\S+)\s*,\s*(\S+)\s*,\s*(.+)\s*$',
            stripped, re.IGNORECASE,
        )
        if four_operand_arith:
            leading = line[:len(line) - len(line.lstrip())]
            patched_lines.append(
                f"{leading}/* replaced (4-op): {stripped} */ mov xzr, xzr"
            )
            continue
        # ---- xzr/wzr as extended operand in add/sub/cmp immediate forms ----
        xzr_extended = re.match(
            r'^(\s*(add|adds|sub|subs|and|ands|cmp|cmn|tst)\s+)'
            r'(\w+)\s*,\s*(x|w)\s*z\s*r\s*,\s*(#?\S+)\s*$',
            stripped,
            re.IGNORECASE,
        )
        if xzr_extended:
            mnemonic = xzr_extended.group(2)  # bare mnemonic
            dest = xzr_extended.group(3)
            zreg = xzr_extended.group(4)
            imm = xzr_extended.group(5)
            leading = line[:len(line) - len(line.lstrip())]
            # Rewrite: `add Xd, xzr, #N` → `mov Xd, xzr` + `add Xd, Xd, #N`
            patched_lines.append(f"{leading}mov {dest}, {zreg}zr")
            patched_lines.append(f"{leading}{mnemonic} {dest}, {dest}, {imm}")
        elif four_operand_arith:
            # Already caught above; this branch is unreachable but kept for safety
            pass
        else:
            patched_lines.append(line)

    # Append a WFI halt loop so the CPU never falls through to unmapped memory.
    # gem5 bare-metal ELFs have no kernel to return to — after the last instruction
    # the PC must halt, not advance into unmapped address space.
    patched_lines.append("")
    patched_lines.append("\tb\t__sdc_halt  /* branch over halt data */")
    patched_lines.append("\t.balign 8")
    patched_lines.append("__sdc_halt:")
    patched_lines.append("\tnop  /* halt: tight loop instead of wfi */")
    patched_lines.append("\tb\t__sdc_halt")
    # Padding NOPs ensure the text section is large enough that even if gem5
    # reads beyond the expected halt loop, it still executes valid instructions.
    # Also guarantees the LOAD segment covers enough bytes to include the loop.
    for _ in range(16):
        patched_lines.append("\tnop")

    return "\n".join(patched_lines)


def _patch_c_for_baremetal(c_source: str) -> str:
    """Transform C source for bare-metal compilation."""
    lines = c_source.splitlines()
    result_lines: List[str] = []
    in_asm_block = False
    asm_buffer: List[str] = []
    asm_re = re.compile(r'__asm__\s*\(')

    # We need to track whether we're inside __asm__(...)
    # to handle the inline assembly specially

    # Approach: identify benchmark asm blocks (sdc_benchmark_body function)
    # and replace FPU instructions with safe alternatives

    # Replace printf with a stub that does nothing (bare-metal has no I/O)
    # The SDC_DIGEST output is essential for diff testing - emit via a simple
    # loop that can be read from gem5 debug output or memory
    printf_stub = """
static int __sdc_printf_count = 0;
static void __sdc_emit_digit(unsigned long long v) {{
    __sdc_printf_count++;
}}
static int printf(const char *fmt, ...) {{
    // Bare-metal: printf writes to a static buffer that gem5 can read
    // from memory after the simulation ends.
    // For now, just increment a counter so we know printf was called.
    extern volatile unsigned long long __sdc_printf_counter;
    __sdc_printf_counter++;
    return 0;
}}
"""

    # Inject the printf stub before the first #include
    patched_lines: List[str] = []
    stub_inserted = False
    for line in lines:
        if not stub_inserted and line.startswith("#include"):
            patched_lines.append(printf_stub)
            stub_inserted = True
        patched_lines.append(line)

    patched = "\n".join(patched_lines)

    # Remove printf/fprintf/fflush that need libc
    # Actually keep them - our stub above handles them

    # Remove FPU/SIMD instructions from asm strings
    patched = _patch_fpu_instructions(patched)

    # Replace exit() calls with infinite loop
    patched = re.sub(
        r'\bexit\s*\([^)]*\)\s*;',
        r'for(;;){ __asm__("wfi"); }  /* exit replaced with halt */',
        patched,
        flags=re.IGNORECASE
    )

    # Remove the description() function that calls exit
    patched = re.sub(
        r'exit\s*\([^)]*\)\s*;',
        r'/* exit removed for bare-metal */',
        patched,
        flags=re.IGNORECASE
    )

    # Ensure main() ends with a halt loop, not fall-through
    # Insert after "return 0;" in main
    patched = re.sub(
        r'(\breturn\s+0\s*;[\s\n]*\})',
        r'\nfor(;;){ __asm__("wfi"); } /* halt */\n}',
        patched,
    )

    return patched


def _run_cmd(cmd: List[str], cwd: Optional[str] = None,
             env: Optional[dict] = None) -> Tuple[int, str, str]:
    """Run a command and return (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(
            cmd,
            cwd=cwd,
            env=env,
            capture_output=True,
            text=True,
            timeout=120,
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return -1, "", "Command timed out"
    except Exception as e:
        return -1, "", str(e)


def _patch_raw_asm_for_baremetal(asm_text: str) -> str:
    """Pre-process raw Microprobe ARM64 assembly for bare-metal assembly.

    Handles instructions that the SDC fuzzing policy generates but that
    aarch64-elf-as (no LSE/SIMD target) cannot assemble.  Each unsupported
    instruction is replaced with ``mov xzr, xzr`` (architectural NOP) so the
    instruction count stays the same, keeping code addresses valid.

    Instructions replaced:
      - ARMv8.1 LSE atomics  (LDSMAX, LDADD, CAS*, LDXR/STXR, …)
      - FP/NEON              (FMLS, FMLA, FNMADD, FMSUB, FNEG, FSUB, …)
      - SIMD loads/stores    (LD1/ST1, LD2/ST2, LD1R, …)
      - Pair memory          (LDP, STP)
      - BR / BRK             (indirect branches with no return address)
      - ADDS/SUBS (flag-setting arithmetic, keep but patch immediates)

    MOVZ/MOVK/MOVN are normalized to lower-case with explicit ``LSL #N``.
    ``adds xN, xzr, #imm`` is rewritten to avoid xzr as extended operand.
    """
    lines = asm_text.splitlines()
    result: List[str] = []
    _nops_emitted = 0  # track for debugging

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------
    def _leading(line: str) -> str:
        """Preserve original leading whitespace exactly."""
        return line[:len(line) - len(line.lstrip())]

    # ------------------------------------------------------------------
    # Pass 1 – normalise MOVZ/MOVK/MOVN and drop unsupported directives
    # ------------------------------------------------------------------
    for line in lines:
        stripped = line.strip()

        # Drop comments and comment-only lines
        if stripped.startswith("//"):
            continue

        # Drop .syntax / .code / .fpu directives that aarch64-elf-as rejects
        if stripped.startswith((".syntax", ".code", ".fpu")):
            continue

        # Drop bare comments that survived previous passes
        if stripped.startswith("/*") or stripped.endswith("*/"):
            continue

        # Pass through section directives and labels
        if not stripped or stripped.startswith((
            ".L", ".LC", ".string", ".byte", ".align", ".type", ".size",
            ".file", ".section", ".data", ".rodata", ".bss", ".ident",
            ".globl", ".global", ".hidden", ".weak", ".fpu", ".code",
            "=", "//", "#", ".uleb", ".sleb", ".arch", ".arch_extension",
        )):
            result.append(line)
            continue

        # Detect a label (line ending with ':')
        if stripped.endswith(":") and not stripped.startswith(
            ("b.", "cbnz", "cbz", "tbnz", "tbz")
        ):
            result.append(line)
            continue

        # ---- MOVZ / MOVK / MOVN normalization ----
        mov_match = re.match(
            r'^(MOVK|MOVZ|MOVN)\s+(\w+),\s*(\d+)\s*,?\s*(.*)$',
            stripped,
            re.IGNORECASE,
        )
        if mov_match:
            mnem_upper, reg, imm_s, rest = mov_match.groups()
            lead = _leading(line)
            rest = rest.strip()

            # bare shift name or empty
            if not rest or rest.upper() in {"LSL", "LSR", "ASR"}:
                result.append(f"{lead}{mnem_upper.lower()} {reg}, {imm_s}, {rest.upper() or 'LSL'} #0")
                continue

            # explicit LSL/LSR/ASR with amount
            sh_match = re.match(
                r'^(LSL|LSR|ASR)\s*#?\s*(\d+)$', rest, re.IGNORECASE
            )
            if sh_match:
                kind = sh_match.group(1).upper()
                amt = int(sh_match.group(2))
                if amt == 0:
                    result.append(f"{lead}{mnem_upper.lower()} {reg}, {imm_s}, {kind} #0")
                else:
                    result.append(
                        f"{lead}/* replaced movk LSL #{amt} */ mov xzr, xzr"
                    )
                continue

            # bare number – treat as LSL amount; MOVZ/MOVK/MOVN require
            # shift ∈ {0, 16, 32, 48}.  Reject anything else with a NOP.
            if re.match(r'^\d+$', rest):
                amt = int(rest)
                if amt not in {0, 16, 32, 48}:
                    result.append(
                        f"{lead}/* replaced movx LSL #{amt} (invalid shift): "
                        f"{stripped} */ mov xzr, xzr"
                    )
                elif mnem_upper.upper() == "MOVK" and amt > 0:
                    result.append(
                        f"{lead}/* replaced movk LSL #{amt} (imm overflow) */ mov xzr, xzr"
                    )
                else:
                    result.append(f"{lead}{mnem_upper.lower()} {reg}, {imm_s}, LSL #{amt}")
                continue

            # plain bare number as last token (e.g. "MOVZ x0, 42, 1")
            if re.match(r'^\d+$', rest):
                amt = int(rest)
                if amt not in {0, 16, 32, 48}:
                    result.append(
                        f"{lead}/* replaced movx LSL #{amt} (invalid shift): "
                        f"{stripped} */ mov xzr, xzr"
                    )
                elif mnem_upper.upper() == "MOVK" and amt > 0:
                    result.append(
                        f"{lead}/* replaced movk LSL #{amt} */ mov xzr, xzr"
                    )
                else:
                    result.append(f"{lead}{mnem_upper.lower()} {reg}, {imm_s}, LSL #{amt}")
                continue

            # fallthrough – emit with explicit LSL #0
            result.append(f"{lead}{mnem_upper.lower()} {reg}, {imm_s}, LSL #0")
            continue

        # bare movz xN, N  (no shift at all)
        bare_movz = re.match(
            r'^(movz|movn|movk)\s+(\w+),\s*(\d+)\s*$', stripped, re.IGNORECASE
        )
        if bare_movz:
            lead = _leading(line)
            result.append(f"{lead}{bare_movz.group(1).lower()} {bare_movz.group(2)}, {bare_movz.group(3)}, LSL #0")
            continue

        # comma form: movz x0, 42, LSL 1  (gcc -S style with comma)
        comma_movz = re.match(
            r'^(movz|movn|movk)\s+(\w+),\s*(\d+)\s*,\s*(\S+)\s*$',
            stripped, re.IGNORECASE,
        )
        if comma_movz:
            mnem, reg, imm_s, shift = comma_movz.groups()
            lead = _leading(line)
            imm_val = int(imm_s)
            sh_m = re.match(r'^(LSL|LSR|ASR)\s*#(\d+)$', shift, re.IGNORECASE)
            if sh_m:
                kind = sh_m.group(1).upper()
                amt = int(sh_m.group(2))
            else:
                kind = "LSL"
                try:
                    amt = int(re.match(r'\d+', shift).group())
                except (ValueError, AttributeError):
                    amt = 0
            # MOVZ/MOVN allow only shift {0, 16, 32, 48}; reject others with a NOP.
            if amt not in {0, 16, 32, 48}:
                result.append(
                    f"{lead}/* replaced movx {kind} #{amt} (invalid shift): "
                    f"{stripped} */ mov xzr, xzr"
                )
            elif amt == 0:
                result.append(f"{lead}{mnem.lower()} {reg}, {imm_s}, {kind} #0")
            elif imm_val <= (0xFFFF >> amt):
                result.append(f"{lead}{mnem.lower()} {reg}, {imm_s}, {kind} #{amt}")
            else:
                result.append(
                    f"{lead}/* replaced movk (LSL #{amt}, imm={imm_val}): {stripped} */ mov xzr, xzr"
                )
            continue

        # ---- 4-operand Microprobe extended-add forms that aarch64-elf-as
        # rejects.  Must be checked BEFORE safe_gpr because 'adds' is in the
        # safe list — the safe_gpr pass-through would bypass this check.
        four_operand_arith = re.match(
            r'^(\s*(add|adds|sub|subs|and|ands|eor|orr|mov)\s+)'
            r'(\S+)\s*,\s*(\S+)\s*,\s*(\S+)\s*,\s*(.+)\s*$',
            stripped, re.IGNORECASE,
        )
        if four_operand_arith:
            lead = _leading(line)
            result.append(f"{lead}/* replaced (4-op): {stripped} */ mov xzr, xzr")
            continue

        # ---- xzr/wzr as extended operand in add/sub/cmp immediate forms ----
        # Form 1: `adds Xd, xzr, #imm` (3 operands, xzr in src1 position)
        xzr_ext = re.match(
            r'^(\s*(add|adds|sub|subs|and|ands|cmp|cmn|tst)\s+)'
            r'(\w+)\s*,\s*(x|w)\s*z\s*r\s*,\s*(#?\S+)\s*$',
            stripped, re.IGNORECASE,
        )
        if xzr_ext:
            mnem = xzr_ext.group(2).lower()
            dest = xzr_ext.group(3)
            zr = xzr_ext.group(4)
            imm = xzr_ext.group(5)
            lead = _leading(line)
            result.append(f"{lead}mov {dest}, {zr}zr")
            result.append(f"{lead}{mnem} {dest}, {dest}, {imm}")
            continue

        # ---- CBNZ/CBZ/TBNZ/TBZ: offset must be a multiple of 4 ----
        # aarch64-elf-as (Binutils 2.46) rejects non-4-aligned offsets.
        branch_match = re.match(
            r'^(\s*)(cbnz|cbz|tbnz|tbz)\s+(\w+)\s*,\s*(-?\d+)\s*$',
            stripped, re.IGNORECASE,
        )
        if branch_match:
            lead = _leading(line)
            offset = int(branch_match.group(4))
            if offset % 4 != 0:
                result.append(
                    f"{lead}/* replaced (misaligned CBNZ offset={offset}): "
                    f"{stripped} */ mov xzr, xzr"
                )
            else:
                result.append(line)
            continue

        # ---- Safe GPR mnemonics (word-boundary) ----
        safe_gpr = re.compile(
            r'^(\s*(adr|adrp|add|adds|sub|subs|and|ands|or|orr|eor|tst|'
            r'mov|mvn|cmp|cmn|'
            r'lsl|lsr|asr|ror|rorx|'
            r'ldur|stur|ldr|str|ldrb|strb|ldrh|strh|'
            r'ldp|stp|'
            r'b|bl|blrl|cbz|cbnz|ret|csel|cset|cinc|cinv|cneg|'
            r'csneg|csinc|cselz|csinc|'
            r'extr|rev|rev16|rev32|cls|clz|movz|movn|movk|'
            r'ubfx|sbfiz|sbfx|bfi|bfx|'
            r'tbz|tbnz|wfi|nop|hlt|svc|eret|brk|'
            r'ldarb|ldarh|ldar|stlrb|stlrh|stlr|'
            r'mrs|msr|'
            r'hint|yield|auti1711|'
            r'ldaxr|stlxr|ldxr|stxr|prfm)\b\s+)',
            re.IGNORECASE,
        )
        if safe_gpr.match(line):
            result.append(line)
            continue

        # ---- Everything else: replace with NOP ----
        lead = _leading(line)
        result.append(f"{lead}/* replaced: {stripped} */ mov xzr, xzr")

    # ------------------------------------------------------------------
    # Pass 2 – emit halt loop + padding
    # ------------------------------------------------------------------
    # gem5 bare-metal ELFs terminate via SVC #0 (ARM64 syscall).
    # gem5's Linux syscall emulation handles this cleanly (exit_group / exit).
    # Even if the syscall is not emulated, the tight halt loop keeps the PC
    # within valid mapped memory, preventing panic at 0x0.
    result.append("")
    result.append("\t.global\t_start")
    result.append("__sdc_halt:")
    result.append("\tnop  /* halt: branch-to-self loop, exit via tick limit */")
    result.append("\tb\t__sdc_halt")
    for _ in range(16):
        result.append("\tnop")

    return "\n".join(result)


def compile_raw_asm_to_elf(
    asm_file: Path,
    elf_file: Path,
    verbose: bool = False,
) -> Tuple[bool, str]:
    """Assemble a raw Microprobe ARM64 assembly file directly to a bare-metal ELF.

    The input is expected to be raw ARM64 assembly (``.s``) generated by
    Microprobe via the ``sdc_fuzzing`` policy and stored in the SDC vault.
    Because Microprobe's ``BareMetalDiffWrapper`` generates FPU/SIMD/LSE
    instructions that ``aarch64-elf-as`` cannot assemble, this function first
    runs a pre-processor that replaces unsupported instructions with
    ``mov xzr, xzr`` (architectural NOP) and normalises MOVZ/MOVK/MOVN syntax.

    Returns (success, message).
    """
    _write_stub_headers()
    _write_linker_script()

    work_dir = asm_file.parent

    # Step 1 – read and pre-process raw assembly
    asm_source = asm_file.read_text(encoding="utf-8")
    patched_asm = _patch_raw_asm_for_baremetal(asm_source)

    patched_asm_file = work_dir / f"{asm_file.stem}_patched.s"
    patched_asm_file.write_text(patched_asm, encoding="utf-8")
    if verbose:
        print(f"  [raw asm patched] {patched_asm_file.name} ({len(patched_asm)} bytes)")

    # Step 2 – assemble to object
    obj_file = work_dir / f"{asm_file.stem}.o"
    asm_cmd = [
        AARCH64_ELF_AS,
        "-march=armv8-a",
        "-o", str(obj_file),
        str(patched_asm_file),
    ]
    rc, stdout, stderr = _run_cmd(asm_cmd, cwd=str(work_dir))
    if rc != 0:
        return False, f"as failed:\n{stderr[:800]}"

    if verbose:
        print(f"  [object]   {obj_file.name}")

    # Step 3 – link to ELF
    ld_cmd = [
        AARCH64_ELF_LD,
        "-T", str(LINKER_SCRIPT),
        "-Map", str(work_dir / f"{asm_file.stem}.map"),
        "-o", str(elf_file),
        str(obj_file),
    ]
    rc, stdout, stderr = _run_cmd(ld_cmd, cwd=str(work_dir))
    if rc != 0:
        return False, f"ld failed:\n{stderr[:800]}"

    if verbose:
        print(f"  [elf]      {elf_file.name}")

    # Verify ELF header
    elf_info_cmd = [AARCH64_ELF_READELF, "-h", str(elf_file)]
    rc2, stdout2, _ = _run_cmd(elf_info_cmd)
    if rc2 == 0:
        for ln in stdout2.splitlines():
            if any(k in ln for k in ["Machine:", "Entry:", "OS/ABI:"]):
                if verbose:
                    print(f"           {ln.strip()}")

    # Clean up intermediate files
    for f in [patched_asm_file, obj_file]:
        try:
            f.unlink()
        except OSError:
            pass

    return True, f"ELF at {elf_file}"


def compile_c_to_elf(
    c_file: Path,
    elf_file: Path,
    verbose: bool = False,
) -> Tuple[bool, str]:
    """Compile a BareMetalDiffWrapper C file to a bare-metal ARM64 ELF.

    Returns (success, message).
    """
    _write_stub_headers()
    _write_linker_script()

    work_dir = c_file.parent

    # Step 1: Read and patch C source
    c_source = c_file.read_text(encoding="utf-8")
    patched_source = _patch_c_for_baremetal(c_source)

    # Write patched source
    patched_c = work_dir / f"{c_file.stem}_bm.c"
    patched_c.write_text(patched_source, encoding="utf-8")
    if verbose:
        print(f"  [patched] {patched_c.name} ({len(patched_source)} bytes)")

    # Step 2: Compile to assembly (-S)
    # Use stub headers so the compiler doesn't need a sysroot
    asm_file = work_dir / f"{c_file.stem}_bm.s"
    compile_cmd = [
        AARCH64_ELF_GCC,
        "-S",
        "-march=armv8-a",
        "-O2",
        "-I", str(STUB_DIR),
        "-fno-lto",
        "-fno-stack-protector",
        "-fno-pie",
        "-fno-stack-check",
        "-fno-exceptions",
        "-fno-rtti",
        "-o", str(asm_file),
        str(patched_c),
    ]

    rc, stdout, stderr = _run_cmd(compile_cmd, cwd=str(work_dir))
    if rc != 0:
        # Save assembly for debugging even on failure
        if verbose:
            print(f"  [compile stderr]: {stderr[:500]}")
        return False, f"gcc -S failed: {stderr[:300]}"

    # Step 2b: Post-process generated assembly
    asm_text = asm_file.read_text(encoding="utf-8")
    asm_text = _patch_asm_for_baremetal(asm_text)
    asm_file.write_text(asm_text, encoding="utf-8")
    if verbose:
        print(f"  [asm patched] {asm_file.name} ({len(asm_text)} bytes)")

    if verbose:
        print(f"  [assembly] {asm_file.name}")

    # Step 3: Assemble to object
    obj_file = work_dir / f"{c_file.stem}_bm.o"
    asm_cmd = [AARCH64_ELF_AS, "-march=armv8-a", "-o", str(obj_file), str(asm_file)]
    rc, stdout, stderr = _run_cmd(asm_cmd, cwd=str(work_dir))
    if rc != 0:
        return False, f"as failed: {stderr[:300]}"

    if verbose:
        print(f"  [object]   {obj_file.name}")

    # Step 4: Link to ELF
    ld_cmd = [
        AARCH64_ELF_LD,
        "-T", str(LINKER_SCRIPT),
        "-Map", str(work_dir / f"{c_file.stem}_bm.map"),
        "-o", str(elf_file),
        str(obj_file),
    ]
    rc, stdout, stderr = _run_cmd(ld_cmd, cwd=str(work_dir))
    if rc != 0:
        return False, f"ld failed: {stderr[:300]}"

    if verbose:
        print(f"  [elf]      {elf_file.name}")

    # Verify ELF
    elf_info_cmd = [AARCH64_ELF_READELF, "-h", str(elf_file)]
    rc2, stdout2, _ = _run_cmd(elf_info_cmd)
    if rc2 == 0:
        for line in stdout2.splitlines():
            if any(k in line for k in ["Machine:", "Entry:", "OS/ABI:"]):
                if verbose:
                    print(f"           {line.strip()}")

    # Clean up intermediate files
    for f in [patched_c, asm_file, obj_file]:
        try:
            f.unlink()
        except OSError:
            pass

    return True, f"ELF at {elf_file}"


def compile_batch(
    c_files: List[Path],
    output_dir: Path,
    verbose: bool = False,
) -> dict:
    """Compile a batch of C files to ELFs.

    Returns dict with success/failure counts and per-file status.
    """
    results = {
        "total": len(c_files),
        "success": 0,
        "failed": 0,
        "details": [],
    }

    output_dir.mkdir(parents=True, exist_ok=True)

    for c_file in c_files:
        stem = c_file.stem  # e.g. "sha1hash.c" → "sha1hash"
        elf_file = output_dir / f"{stem}.elf"

        success, msg = compile_c_to_elf(c_file, elf_file, verbose=verbose)
        results["details"].append({
            "c_file": str(c_file),
            "elf_file": str(elf_file),
            "success": success,
            "message": msg,
        })
        if success:
            results["success"] += 1
        else:
            results["failed"] += 1
            if verbose:
                print(f"  FAILED: {c_file.name}: {msg}")

    return results


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Bare-metal ARM64 C→ELF compiler")
    parser.add_argument("c_file", type=Path, help="Input .c file")
    parser.add_argument("-o", "--output", type=Path, required=True, help="Output .elf file")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    args = parser.parse_args()

    success, msg = compile_c_to_elf(args.c_file, args.output, verbose=args.verbose)
    print(msg)
    sys.exit(0 if success else 1)
