# Copyright 2026
# Licensed under the Apache License, Version 2.0

"""ARM64 assembly wrapper definitions."""

from __future__ import absolute_import

from microprobe.code import get_wrapper

__all__ = ["Arm64AsmWrapper"]


class Arm64AsmWrapper(get_wrapper("Assembly")):
    """Assembly wrapper with ARM64-specific directives."""

    def headers(self):
        return "\n".join(
            [
                "// ARM64 Assembly Code",
                "// Generated by Microprobe",
                ".arch armv8-a",
                ".text",
                "",
            ]
        )

    def footer(self):
        return "\n// End of generated code\n"
