# Copyright 2026
# Licensed under the Apache License, Version 2.0

"""
ARM64 Assembly Wrapper
"""

from __future__ import absolute_import, print_function

from microprobe.code.wrapper import AsmWrapper


class Arm64AsmWrapper(AsmWrapper):
    """ARM64 Assembly output wrapper."""
    
    def __init__(self, **kwargs):
        super(Arm64AsmWrapper, self).__init__(**kwargs)
        self._architecture = "aarch64"
    
    def _header(self):
        """Generate assembly header."""
        return [
            "// ARM64 Assembly Code",
            "// Generated by Microprobe",
            "",
            ".arch armv8-a",
            ".text",
            ""
        ]
    
    def _footer(self):
        """Generate assembly footer."""
        return [
            "",
            "// End of generated code"
        ]
    
    def _declare_label(self, label):
        """Declare a label."""
        return f"{label}:"
    
    def _declare_global(self, name):
        """Declare a global symbol."""
        return f".global {name}"
    
    def _comment(self, text):
        """Generate a comment."""
        return f"// {text}"
